### PR TITLE
Adds analog camera and other controller options

### PR DESCRIPTION
**Pull request by Mr-Wiseguy**
Adds an optional analog camera mode, similar to later entries in the series.
Also adds camera inversion settings for aiming and analog cam.

### CODE REVIEW

**Comment by theboy181** [comment]
Tested this out and I was hoping that a few items could be addressed with the camera changes. 

1. Make it so that pressing Z will still automatically reset the camera in the direction that Link is facing.
2. Explain if the camera is not supposed to work while swimming, would like it to work not sure why it might not.
3. Add a sprint button so if feels like Dark Souls.. JK!! 


Felt really good, but would like to see 1, and 2 improved.

**Comment by Mr-Wiseguy** [comment]
1 and 2 are both part of the changes I'm currently working on, Epona will also work as well. This is just a draft PR so there are other changes pending as well.

**Comment by Marcelo20XX** [comment]
Could you add perhaps an analog range modifier? I mean like if you press a key i.e. LSHIFT you can make Link move at 50% speed allowing him to walk. It's the only feature I am missing from emulators.

**Comment by Mr-Wiseguy** [comment]
> Could you add perhaps an analog range modifier? I mean like if you press a key i.e. LSHIFT you can make Link at 50% speed allowing him to walk. It's the only feature I am missing from emulators.

Please open this in a separate feature request as it's not related to this PR.

**Comment by theboy181** [comment]
> 1 and 2 are both part of the changes I'm currently working on, Epona will also work as well. This is just a draft PR so there are other changes pending as well.

looking forward to what you are cooking!

**Comment by theboy181** [comment]
Yep! This latest version plays much better. What about First Person modes? Can that be added to both sticks, or would it just feel funny?

**Comment by theboy181** [comment]
Tested the control changes this morning. It actually doesn't fell that wrong. I kind of wanted to be able to move around in first person mode with the changes. :p

I was confused as to why you change it so you needed to select Invert Y though. I am OK with this change, however it is a bit odd as it caters to players are not from the N64 era where default controls are "down is up and up is down". I feel that it moves away from the games original settings and confuses those who know this. ( we are going for a modern game 
play experience though) 


SIDE NOTE: I have been waiting to see if you will increase the draw distance in the game for its many objects. Is this something that you feel can be achieved and will see the light of  day. Sorry to post here, just not sure how I can get access to you in real time.

**Pull request merged**
