### PR TITLE
CI: Build aarch64 linux

### PR DESCRIPTION
**Pull request by dcvz**

### CODE REVIEW

**Comment by nightlark** [comment]
What are the "blaze/" runners? I've been using Cirrus CI for ARM64 CI jobs in another open source project, but something that can use existing GHA workflows looks much nicer to manage (+ all artifacts in one place).

**Comment by dcvz** [comment]
> What are the "blaze/" runners? I've been using Cirrus CI for ARM64 CI jobs in another open source project, but something that can use existing GHA workflows looks much nicer to manage (+ all artifacts in one place).

They're from: https://runblaze.dev/

**Comment by dcvz** [comment]
@theofficialgman since you're the one person I know using ARM64 with Vulkan, could I ask you to validate the binary and AppImage generated for ARM64?

They're here: https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9244558317

**Comment by mrcmunir** [comment]
> @theofficialgman since you're the one person I know using ARM64 with Vulkan, could I ask you to validate the binary and AppImage generated for ARM64?
> 
> They're here: https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9244558317

iI'm tested  Appimage working with Tegra TX1 device.
Screenshot from 2024-05-27 12-14-37
Screenshot from 2024-05-27 12-15-56

Not detected issues

**Comment by dcvz** [comment]
> > @theofficialgman since you're the one person I know using ARM64 with Vulkan, could I ask you to validate the binary and AppImage generated for ARM64?
> 
> > 
> 
> > They're here: https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9244558317
> 
> 
> 
> iI'm tested  Appimage working with Tegra TX1 device.
> 
> Screenshot from 2024-05-27 12-14-37
> 
> Screenshot from 2024-05-27 12-15-56
> 
> 
> 
> Not detected issues
> 
> 
> 
> 

Muchas gracias por verificarlo! Thanks for testing!

**Comment by theofficialgman** [comment]
@dcvz I'm confused who's runners you are using here. I thought blaze only has macos arm64 runners? What is your cost for this Linux arm64 runner?

**Comment by dcvz** [comment]
@nightlark Linux ARM64 is in private beta, but you can email the Blaze team if its something that interests you.

**Pull request merged**
