### PR TITLE
Update Ubuntu build instructions

### PR DESCRIPTION
**Pull request by lkoger**
Current instructions to build in Ubuntu appear to be incorrect.

A package name needed to be updated for the apt-get command:
* Updated `ninja` to be `ninja-build`.

Some cmake variables needed to be set and/or updated in one of the example cmake commands:
* Updated `DCMAKE_CXX_COMPILER=clang++` to `DCMAKE_CXX_COMPILER=clang++-15`
* Updated `-DCMAKE_C_COMPILER=clang` to `-DCMAKE_C_COMPILER=clang-15`
* Added `-DPATCHES_C_COMPILER=clang-15`

I updated the instructions with what I've run in my local environment, but it might be worth updating instructions to be in line with what is currently done via the [validation Github action](https://github.com/Zelda64Recomp/Zelda64Recomp/blob/d99a84f04f6803a0df49383b6a05f4253a1b7c0a/.github/workflows/validate.yml#L90) instead. This workflow explicitly sets a few more cmake variables and uses clang-17 over clang-15.

### Build Artifacts
- [Zelda64Recompiled-Linux-ARM64-Debug.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021000132.zip)
- [Zelda64Recompiled-AppImage-ARM64-Debug.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021000955.zip)
- [Zelda64Recompiled-Windows-Debug.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021001115.zip)
- [Zelda64Recompiled-Linux-ARM64-Release.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021002740.zip)
- [Zelda64Recompiled-Windows-Release.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021002959.zip)
- [Zelda64Recompiled-AppImage-ARM64-Release.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021003920.zip)
- [Zelda64Recompiled-AppImage-X64-Debug.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021004172.zip)
- [Zelda64Recompiled-AppImage-X64-Release.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021004173.zip)
- [Zelda64Recompiled-Linux-X64-Debug.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021004174.zip)
- [Zelda64Recompiled-Linux-X64-Release.zip](https://nightly.link/Zelda64Recomp/Zelda64Recomp/actions/artifacts/2021004175.zip)

### CODE REVIEW

**Comment by Joomzie** [comment]
It's also worth mentioning that `g++-12` should be included as a build dependency. Without it, `clang` will complain about not being able to find `filesystem`. Not sure if this is an issue on Ubuntu, but it was causing problems for me on Pop!_OS.

**Comment by Mr-Wiseguy** [comment]
There's no need to pin a specific clang version, I'd prefer it if the user's default clang installation was used so that this guide doesn't become outdated when distros stop shipping a package for the clang version in the instructions.

> It's also worth mentioning that g++-12 should be included as a build dependency. Without it, clang will complain about not being able to find filesystem. Not sure if this is an issue on Ubuntu, but it was causing problems for me on Pop!_OS.

That's likely just a result of Pop!_OS's latest release being over 2 years ago. I haven't run into that issue with other distros, so it's likely just that installing g++-12 is also upgrading your libstdc++ which gives you the missing C++20 features.

**Comment by Joomzie** [comment]
> That's likely just a result of Pop!_OS's latest release being over 2 years ago. I haven't run into that issue with other distros, so it's likely just that installing g++-12 is also upgrading your libstdc++ which gives you the missing C++20 features.

Yeah, I had a hunch. It's become harder and harder to have a reliable build environment for most things, and I'm using a Frankenstein I've cobbled together in order to compensate. I plan to resolve this with a fresh install, but 24.04 needs a bit more time in the oven before I can justify installing it on a production machine. It's the only reason why I'm still on 22.04. It's also getting rather difficult to remain patient, though, heh.

**Comment by lkoger** [comment]
> There's no need to pin a specific clang version, I'd prefer it if the user's default clang installation was used so that this guide doesn't become outdated when distros stop shipping a package for the clang version in the instructions.
> 

I had assumed that clang-15 was required, due to the apt-get example command. If that's not the case, all of the CMake files and build instructions are good to go and only the apt-get packages need to be updated.

**Comment by lkoger** [comment]
Updated.

**Review by Mr-Wiseguy — APPROVED** [review]

**Comment by Mr-Wiseguy** [comment]
Thanks for the PR!

**Pull request merged**
