### PR TITLE
add better double SoT

### PR DESCRIPTION
**Pull request by danielryb**
This pull request allows the player to choose which hour to skip to with Double Song of Time. 

**How to use:**
To choose an hour use the x-axis of the left analog. Hold the analog for faster selection. 

image

**I checked it in the following situations:** 

- day -> dawn of the next day
- day -> night (before and after midnight)
- rain -> no rain (before and after midnight)
- day/night -> midnight of the carnival (Termina Field and South Clocktown)
- day/night -> final hours (after midnight) (Termina Field and South Clocktown)

### CODE REVIEW

**Comment by danielryb** [comment]
I apologize for force pushes.

I removed most of the actor patches and replaced them with actor specific fixes called directly after the time skip gets applied. I think this is a better approach as it leaves most of the code intact, reduces the room for possible errors to the usage of DSoT only and appears to be cleaner overall.

I also added toggle for this feature in the general options. Currently it appears out of bounds but I decided to not address it. Mainly because I'm not experienced with RmlUi but I also think it exceeds the topic of this pull request.

**Comment by Mr-Wiseguy** [comment]
Thanks for the PR! This is a really cool feature and the implementation is great, but I do think it falls more within mod territory since it changes how the song works pretty heavily. I don't have any concrete guidelines as to what I think fits in the base project vs what should be a mod, but I think a good rule of thumb is that built-in changes should be things you can just choose not to use (like your song of soaring skip PR or dpad masks) or shouldn't affect gameplay. As you've noticed the list of options is already getting a bit unwieldy, so adding more options isn't very desirable and I'd rather keep it to things that I feel are absolutely necessary. Autosaving is probably the biggest exception, with the reasoning being that modern systems just aren't stable enough in my opinion to allow multi-hour game sessions without some insurance. I realize this is probably not a decision everyone will agree with, but one of my main goals for this project is that it's very easy to pick up, so I want to keep the menus in the base project from getting intimidating to casual players.

With that said, definitely keep the code around as you'll be able to turn it into a mod very easily when the modding framework is ready (which is what I'm working on currently). Writing mods will be almost identical to writing patches, with the main difference being that they're recompiled from the launcher so they can be loaded dynamically. There will also be a system for mods to add their own menus, which you could take advantage of here if you want any customizable functionality. When that time comes I'd be happy to help you convert this into a mod if you're interested, and it'd serve as a great example mod to demonstrate what the modding framework can do. We can even include it as a built-in mod (meaning it'd show up in the mod menu from a fresh install) if you want, since I do think it's a feature a lot of people would like.

The other note I have is that this patch changes some pretty centralized functions, namely Message_Update for example. This can be a problem because it means mods that change that function will have to deal with conflicts from it being changed in the base project. This is no fault of your own, rather it indicates that recomp should probably get some hook or API here to allow less invasive changes to behaviors. Maybe recomp needs an API to allow replacing vanilla messages that can be called from an initialization function somewhere? Definitely open to suggestions for API and hook additions to facilitate changes like this one more easily.

**Comment by danielryb** [comment]
>Thanks for the PR! This is a really cool feature and the implementation is great, but I do think it falls more within mod territory since it changes how the song works pretty heavily. I don't have any concrete guidelines as to what I think fits in the base project vs what should be a mod, but I think a good rule of thumb is that built-in changes should be things you can just choose not to use (like your song of soaring skip PR or dpad masks) or shouldn't affect gameplay. As you've noticed the list of options is already getting a bit unwieldy, so adding more options isn't very desirable and I'd rather keep it to things that I feel are absolutely necessary. Autosaving is probably the biggest exception, with the reasoning being that modern systems just aren't stable enough in my opinion to allow multi-hour game sessions without some insurance. I realize this is probably not a decision everyone will agree with, but one of my main goals for this project is that it's very easy to pick up, so I want to keep the menus in the base project from getting intimidating to casual players.

The clarity and elegant approach of this project is something I'm in awe with, so this is completely understandable.

>With that said, definitely keep the code around as you'll be able to turn it into a mod very easily when the modding framework is ready (which is what I'm working on currently). Writing mods will be almost identical to writing patches, with the main difference being that they're recompiled from the launcher so they can be loaded dynamically. There will also be a system for mods to add their own menus, which you could take advantage of here if you want any customizable functionality. When that time comes I'd be happy to help you convert this into a mod if you're interested, and it'd serve as a great example mod to demonstrate what the modding framework can do. We can even include it as a built-in mod (meaning it'd show up in the mod menu from a fresh install) if you want, since I do think it's a feature a lot of people would like.

Of course, I'd be honored to!

>The other note I have is that this patch changes some pretty centralized functions, namely Message_Update for example. This can be a problem because it means mods that change that function will have to deal with conflicts from it being changed in the base project. This is no fault of your own, rather it indicates that recomp should probably get some hook or API here to allow less invasive changes to behaviors. Maybe recomp needs an API to allow replacing vanilla messages that can be called from an initialization function somewhere? Definitely open to suggestions for API and hook additions to facilitate changes like this one more easily.

I'm not sure. How exactly is modding going to work? Will modded functions replace their vanilla equivalents, or will they get injected at a specified point?

**Comment by dcvz** [comment]
> I'm not sure. How exactly is modding going to work? Will modded functions replace their vanilla equivalents, or will they get injected at a specified point?

The first version will be like the former: modded functions will replace their vanilla counterparts. Functions that ZeldaRecomp has updated will not be able to be replaced (at first, but will change down the line). But as was pointed out, this won't work very well for large or crucial methods like `Message_Update` so it shows that we'll likely also need a hook system (general or for specific methods) that would allow mods to hook themselves into specific parts of the code or replace things without replacing whole methods.

**Comment by Mr-Wiseguy** [comment]
Mods will also be able to export API functions that other mods are able to call, and then those would mark the first mod as a dependency. There will probably be some sort of "core" mod that the project has which other mods can mark as a dependency to expose a lot of common functionality, something like a hook in Message_Update to use different text for the Song of Double Time message box could be a function in that core mod's API.

**Comment by Mr-Wiseguy** [comment]
@danielryb Sorry it took so long, but the modding framework is now in early testing and usable for making code mods like this one. There's a mod template available here: https://github.com/Zelda64Recomp/MMRecompModTemplate with instructions on how to set things up and an example function patch. You'll need to use the modding branch of this repo, but there just so happens to be a PR open targeting that branch open right now so you can just download the CI artifact: https://github.com/Zelda64Recomp/Zelda64Recomp/pull/487.

**Comment by LittleCube-hax** [comment]
Hi daniel! Don't want to ping you again, but on Wiseguy's note I wanted to let you know that I'm ready and willing to help you convert this to a mod, as I'm interested in depending on it for another mod I'm making.

It looks like I'll have to add some events to make the mod work well with `Message_Update`, which I want to discuss with you a bit so we can make it generally useful, and other mods will also be able to use those events in the future.

**Comment by danielryb** [comment]
Sorry for the late response. I had mention notifications set to mail only.

> @danielryb Sorry it took so long, but the modding framework is now in early testing and usable for making code mods like this one. There's a mod template available here: https://github.com/Zelda64Recomp/MMRecompModTemplate with instructions on how to set things up and an example function patch. You'll need to use the modding branch of this repo, but there just so happens to be a PR open targeting that branch open right now so you can just download the CI artifact: #487.

I've just converted the patch to a [mod](https://github.com/danielryb/MMRecompBetterDoubleSoT). Currently it doesn't use any hooks, but everything seems to be working correctly.

The process was mostly seamless, except one [line](https://github.com/danielryb/MMRecompBetterDoubleSoT/blob/85671b494b2bcde4f465b5673abd9cffe2bab989/src/event_patches.c#L266) where the automatic relocation doesn't seem to work properly. I also experienced a problem during the compilation of the modding branch where clang couldn't resolve an [include](https://github.com/Zelda64Recomp/Zelda64Recomp/blob/4767424aee4716eabf7bf2b6cb4ab576066f6218/include/zelda_render.h#L9). I made sure I'm using the correct version of the compiler, but the problem persisted. Eventually i just changed the path to be more precise.


> Hi daniel! Don't want to ping you again, but on Wiseguy's note I wanted to let you know that I'm ready and willing to help you convert this to a mod, as I'm interested in depending on it for another mod I'm making.
> 
> It looks like I'll have to add some events to make the mod work well with `Message_Update`, which I want to discuss with you a bit so we can make it generally useful, and other mods will also be able to use those events in the future.

Thanks! Would you like to move the conversation somewhere else? I have a discord with the same name. You can add me there.

**Comment by Mr-Wiseguy** [comment]
Closing this PR since we sorted out the issue with the relocation in DMs and because adding this as a built-in mod makes more sense to do as a new PR instead of working off this one. That can happen once I have a system set up for building and embedding built-in mods.

**Pull request closed without merging**
