### PR TITLE
Update RT64 for HD texture framework and DXIL linker

### PR DESCRIPTION
**Pull request by Reonu**
See https://github.com/rt64/rt64/pull/34 for details

Wiseguy: This PR doesn't include the actual menu for loading texture packs, which is still being worked on. It only has the RT64 update that introduces texture pack support.

### CODE REVIEW

**Comment by Nantris** [comment]
I wonder how close we are to HD texture packs? I just started replaying Majora's Mask after 20 years and now I wonder if I shouldn't wait another couple weeks to continue.

Bonus question: Is there any way to port emulator progress to the recomped version? And a preemptive apology, because I know the latter question is a bit beyond the scope of the issue tracker.

**Comment by TiimmyTuurner** [comment]
I would say continue now, I been playing around with it for a week now, it’s really stable and runs great.

**Comment by Nantris** [comment]
Thanks for your reply @TiimmyTuurner and sorry, I was unclear - I started on an emulator since I didn't know this was on the horizon.

**Comment by ryzendew** [comment]
i want to test it and i followed the https://github.com/rt64/rt64/pull/34 thing here and enabled the dev mode but f1 didn't anything. 

was wondering if i need the debug build also or if there is another way.

**Comment by Reonu** [comment]
Are you on Linux? The F1 menu currently does not work on Linux (this will be addressed in the future). For now if you want to access the F1 menu you have to run the Windows version with Proton (which works fine)

**Comment by ryzendew** [comment]
> Are you on Linux? The F1 menu currently does not work on Linux (this will be addressed in the future). For now if you want to access the F1 menu you have to run the Windows version with Proton (which works fine)

ok thank you i will do that

**Comment by ryzendew** [comment]
image
confirm it's working well

**Comment by DonelBueno** [comment]
> image confirm it's working well

Is this Nerrel's texture pack? Where did you find it in DDS?

**Comment by EliazarGtez** [comment]
Where did you get the texture pack in DDS format?

**Comment by ryzendew** [comment]
> > image confirm it's working well
> 
> Is this Nerrel's texture pack? Where did you find it in DDS?

it's png not DDS

**Comment by EliazarGtez** [comment]
I cannot find the "texture tab" to select the location of the texture pack. Can you help me to find it?

**Comment by HenryHAdams** [comment]
> I cannot find the "texture tab" to select the location of the texture pack. Can you help me to find it?

same

**Comment by DagothUrTheFalse** [comment]
I cant get it working under proton so I eagerly await the ability to use the hd textures on linux once its added.

**Comment by p3k22** [comment]
yay

To the people who are asking about the texture tab. Here's how it's done.

Go here: [Pull Request](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/262/checks) and under where it says "Artifacts", download the relevant zip file. Unzip it anywhere.

Navigate to "C:\Users\<username>\AppData\Local\Zelda64Recompiled" and set "developer_mode": true in the file "graphics.json".

For the HD Textures download Nerrels HD texture pack [here](https://evilgames.eu/texture-packs/files/mm-reloaded-v10.4.0-gliden64-png_0.5x.zip) 
Extract this folder anywhere. 
Within the extracted folder, place [rt64.json](https://github.com/rt64/rt64/files/15444631/rt64.json) inside it too.

Finally, launch Zelda64Recompiled. Press F1. Voilà!
Go to the textures tab, hit Load Directory, point it to the folder you put rt64.json in and you should be good to go.

**Comment by DagothUrTheFalse** [comment]
Still cant do it on linux though since the debug menu isn't available on there, yeah?

**Comment by Reonu** [comment]
> Still cant do it on linux though since the debug menu isn't available on there, yeah?

You can by running the Windows version via Proton, that being said the F1 menu will be added to the Linux build eventually.

**Comment by DagothUrTheFalse** [comment]
> 
> You can by running the Windows version via Proton, that being said the F1 menu will be added to the Linux build eventually.

I could not get it working under proton. Stated that a bit ago but I think ya missed that comment.

**Comment by Reonu** [comment]
> > > Still cant do it on linux though since the debug menu isn't available on there, yeah?
> > 
> > 
> > You can by running the Windows version via Proton, that being said the F1 menu will be added to the Linux build eventually.
> 
> I could not get it working under proton. Stated that a bit ago but I think ya missed that comment.

Did you go to the graphics.json file in the %LOCALAPPDATA% folder inside of the wineprefix for your Zelda 64 Recompiled Steam entry, and enable the debug mode?

**Comment by DagothUrTheFalse** [comment]
> 
> Did you go to the graphics.json file in the %LOCALAPPDATA% folder inside of the wineprefix for your Zelda 64 Recompiled Steam entry, and enable the debug mode?

I could not launch it at all under proton, I do not know the specific reason, I tried multiple proton versions and tried wine config to make sure the local dlls were used. I'm not sure this is the best place to discuss my technical issues with that however.

**Comment by Reonu** [comment]
Proton isn't officially supported, it just happens to work, so if it's not working for you you'll have to wait until the F1 menu is added to the Linux build (or until HD textures are properly implemented which will have a proper user-facing UI). With that being said if you want to discuss Proton issues further, you'd have to open a separate issue and see if other people can help you, as this is starting to get off-topic as you mentioned.

**Comment by ryzendew** [comment]
> > Did you go to the graphics.json file in the %LOCALAPPDATA% folder inside of the wineprefix for your Zelda 64 Recompiled Steam entry, and enable the debug mode?
> 
> I could not launch it at all under proton, I do not know the specific reason, I tried multiple proton versions and tried wine config to make sure the local dlls were used. I'm not sure this is the best place to discuss my technical issues with that however.

just use normal wine-staging or wine-devel with winetricks and winettricks -q vkd3d is needed

**Comment by ripnetuk** [comment]
Seems to work nicely for me (i7 / intel integrated gfx / directX api), cant wait until this is in the official release.

Edit: played a bit more (on my actual gaming devices legion go). This is stunning, absolutely amazing looking now. Thank you!

Edit2: any chance of persisting the textures over loads?

**Comment by albusgod** [comment]
> yay
> 
> To the people who are asking about the texture tab. Here's how it's done.
> 
> Go here: [Pull Request](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/262/checks) and under where it says "Artifacts", download the relevant zip file. Unzip it anywhere.
> 
> Navigate to "C:\Users<username>\AppData\Local\Zelda64Recompiled" and set "developer_mode": true in the file "graphics.json".
> 
> For the HD Textures download Nerrels HD texture pack [here](https://evilgames.eu/texture-packs/files/mm-reloaded-v10.4.0-gliden64-png_0.5x.zip) Extract this folder anywhere. Within the extracted folder, place [rt64.json](https://github.com/rt64/rt64/files/15444631/rt64.json) inside it too.
> 
> Finally, launch Zelda64Recompiled. Press F1. Voilà! Go to the textures tab, hit Load Directory, point it to the folder you put rt64.json in and you should be good to go.

i manage to get the HD textures working but only in n64recomp 1.0 :(
the texture tab doesnt show on the last 1.1.1

**Comment by ripnetuk** [comment]
> > yay
> > To the people who are asking about the texture tab. Here's how it's done.
> > Go here: [Pull Request](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/262/checks) and under where it says "Artifacts", download the relevant zip file. Unzip it anywhere.
> > Navigate to "C:\Users\AppData\Local\Zelda64Recompiled" and set "developer_mode": true in the file "graphics.json".
> > For the HD Textures download Nerrels HD texture pack [here](https://evilgames.eu/texture-packs/files/mm-reloaded-v10.4.0-gliden64-png_0.5x.zip) Extract this folder anywhere. Within the extracted folder, place [rt64.json](https://github.com/rt64/rt64/files/15444631/rt64.json) inside it too.
> > Finally, launch Zelda64Recompiled. Press F1. Voilà! Go to the textures tab, hit Load Directory, point it to the folder you put rt64.json in and you should be good to go.
> 
> i manage to get the HD textures working but only in n64recomp 1.0 :( the texture tab doesnt show on the last 1.1.1

Hi,
Unless I've misunderstood something, this pull request is what enables the texture loading, so we need to download the binary artifact created when it was built, which was 1.0 based

At some point hopefully it will get re-based on the current release, and hopefully the pull will be accepted. It does look absolutely lovely (but to be fair, the high res poly rendering already gets us 80% there)

The only thing i miss from the 1.1 release is the better camera with deku shrub. I already keep the save folder in git [commit message: melted ice] so the auto backup isnt really needed for me.

In any case, I would like to once again raise my hat to the author of this amazing rebirth of an amazing game. Its trumped the likes of GTA4 and RDR2 in my gaming queue.

**Comment by albusgod** [comment]
im kinda new in github but thanks for the reply, indeed the HD textures works only on that build, but it works perfect at the time, no major bug texture or glitches, 
i miss the Dpad ocarina and the better camera with deku shrub but we just have to wait.
a big thanks to all the dev team, youre making history with this recompiler.


> > > yay
> > > To the people who are asking about the texture tab. Here's how it's done.
> > > Go here: [Pull Request](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/262/checks) and under where it says "Artifacts", download the relevant zip file. Unzip it anywhere.
> > > Navigate to "C:\Users\AppData\Local\Zelda64Recompiled" and set "developer_mode": true in the file "graphics.json".
> > > For the HD Textures download Nerrels HD texture pack [here](https://evilgames.eu/texture-packs/files/mm-reloaded-v10.4.0-gliden64-png_0.5x.zip) Extract this folder anywhere. Within the extracted folder, place [rt64.json](https://github.com/rt64/rt64/files/15444631/rt64.json) inside it too.
> > > Finally, launch Zelda64Recompiled. Press F1. Voilà! Go to the textures tab, hit Load Directory, point it to the folder you put rt64.json in and you should be good to go.
> > 
> > 
> > i manage to get the HD textures working but only in n64recomp 1.0 :( the texture tab doesnt show on the last 1.1.1
> 
> Hi, Unless I've misunderstood something, this pull request is what enables the texture loading, so we need to download the binary artifact created when it was built, which was 1.0 based
> 
> At some point hopefully it will get re-based on the current release, and hopefully the pull will be accepted. It does look absolutely lovely (but to be fair, the high res poly rendering already gets us 80% there)
> 
> The only thing i miss from the 1.1 release is the better camera with deku shrub. I already keep the save folder in git [commit message: melted ice] so the auto backup isnt really needed for me.
> 
> In any case, I would like to once again raise my hat to the author of this amazing rebirth of an amazing game. Its trumped the likes of GTA4 and RDR2 in my gaming queue.

**Comment by ripnetuk** [comment]
> im kinda new in github but thanks for the reply, indeed the HD textures works only on that build, but it works perfect at the time, no major bug texture or glitches, i miss the Dpad ocarina and the better camera with deku shrub but we just have to wait. a big thanks to all the dev team, youre making history with this recompiler.

You know you can control the Ocarina with the right joystick, even when free camera is enabled.. I got quite a way into the game mentally translating to the mapped c buttons before I realised that :) that totally mitigates the lack of dpad control for me.

**Comment by DarioSamo** [comment]
> Edit2: any chance of persisting the textures over loads?

The idea behind the feature is Recomp itself will take care of managing the texture pack and telling RT64 to load it through a nicer menu like the rest of the options. This is very much just a feature hidden behind a developer menu at the moment because it's very much only for testing the feature.

**Comment by Nazeeb01** [comment]
> im kinda new in github but thanks for the reply, indeed the HD textures works only on that build, but it works perfect at the time, no major bug texture or glitches, i miss the Dpad ocarina and the better camera with deku shrub but we just have to wait. a big thanks to all the dev team, youre making history with this recompiler.
> 
> > > > yay
> > > > To the people who are asking about the texture tab. Here's how it's done.
> > > > Go here: [Pull Request](https://github.com/Zelda64Recomp/Zelda64Recomp/pull/262/checks) and under where it says "Artifacts", download the relevant zip file. Unzip it anywhere.
> > > > Navigate to "C:\Users\AppData\Local\Zelda64Recompiled" and set "developer_mode": true in the file "graphics.json".
> > > > For the HD Textures download Nerrels HD texture pack [here](https://evilgames.eu/texture-packs/files/mm-reloaded-v10.4.0-gliden64-png_0.5x.zip) Extract this folder anywhere. Within the extracted folder, place [rt64.json](https://github.com/rt64/rt64/files/15444631/rt64.json) inside it too.
> > > > Finally, launch Zelda64Recompiled. Press F1. Voilà! Go to the textures tab, hit Load Directory, point it to the folder you put rt64.json in and you should be good to go.
> > > 
> > > 
> > > i manage to get the HD textures working but only in n64recomp 1.0 :( the texture tab doesnt show on the last 1.1.1
> > 
> > 
> > Hi, Unless I've misunderstood something, this pull request is what enables the texture loading, so we need to download the binary artifact created when it was built, which was 1.0 based
> > At some point hopefully it will get re-based on the current release, and hopefully the pull will be accepted. It does look absolutely lovely (but to be fair, the high res poly rendering already gets us 80% there)
> > The only thing i miss from the 1.1 release is the better camera with deku shrub. I already keep the save folder in git [commit message: melted ice] so the auto backup isnt really needed for me.
> > In any case, I would like to once again raise my hat to the author of this amazing rebirth of an amazing game. Its trumped the likes of GTA4 and RDR2 in my gaming queue.

looks like you can still use the textures on 1.1.1 when you click [here ](https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9590980274). the windows release one worked for me

**Comment by ripnetuk** [comment]
Awesome :) will give it a try tonight before my next attempt to beat that blasted skeleton to the east.

**Comment by ripnetuk** [comment]
Hi.. can confirm that it works brilliantly, but I now have a new issue... (that will go away when this makes mainline...)

I cant operate the ImGui popup menu on my device (Legion Go) with an external display. On the internal display, I can use the touchscreen to operate it, but Z64R hides the mouse cursor, so when im using an external screen, I cannot operate the debug menu, and cannot therefore enable the lovely HD textures.

Im trying to make a hacked build (for use until this makes the main release) that automatically loads the textures without having to use the F5 debug menu, or just to add some keyboard shortcuts to the n64_state.cpp file so I can operate the debug menu on the 2nd screen.

However, it looks like there is a git submodule which is not public in this branch (hd_textures) which is preventing me from checking out XXHash:


Cloning into 'C:/git/other/Zelda64Recomp/lib/N64ModernRuntime/thirdparty/xxHash'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:Cyan4973/xxHash.git' into submodule path 'C:/git/other/Zelda64Recomp/lib/N64ModernRuntime/thirdparty/xxHash' failed

I'm not sure if this submodule is essential to get a build out - i will continue through the instructions on build.md to get the decompressed rom and the elf, and then try building.

**Comment by Mr-Wiseguy** [comment]
Thank you for your interest. This branch is meant for developers and texture pack authors to test with, so the UI is not finished. The F1 menu is just for debugging purposes. When this actually launches, there will be a proper menu for loading texture packs. As such, this branch is not supported for end users and I'd suggest just waiting for the proper release to play with HD texture support.

**Comment by ripnetuk** [comment]
> Thank you for your interest. This branch is meant for developers and texture pack authors to test with, so the UI is not finished. The F1 menu is just for debugging purposes. When this actually launches, there will be a proper menu for loading texture packs. As such, this branch is not supported for end users and I'd suggest just waiting for the proper release to play with HD texture support.

Hi
I totally get that, and am happy to continue using the dev menu to test the texture pack. So far it has worked perfectly and looks beautiful. 

This end user is delighted with the 1.1 build with the texture pack.

I will make another attempt to figure out the build process on main branch at some point
Thanks, this is the best way I've found to play the only 3d zelda I haven't yet played to the end. Loving it

**Comment by baconVritters** [comment]
Can't seem to get the texture tab to load. Here's my steps

1. Go to %localappdata% (path C:\Users\myname\AppData\Local), then open the Zelda64Recompiled folder

2. Open graphics.json in notepad and change line 4 to 
    "developer_mode": true, 
then save and close.

3. On the Zelda64Recomp github webpage, go to 
actions -> validate-internal -> (whichever is most recent) WIP HD texture support -> Artifacts

4. There are two options for Windows files to download. 

The first is "Zelda64Recompiled-Windows-Debug", which opens a windows command prompt, then immediately closes it. I assumed this meant it needed to be opened via command prompt. I opened a new windows command prompt, cd'd into my Majoras Mask recomp folder, and typed "Zelda64Recompiled.exe" to run the executable. Nothing happened.

The second is "Zelda64Recompiled-Windows-Release", which successfully opens Majora's Mask Recomp 1.1.1, but pressing f1 does nothing. 

If you know where I made an error, please let me know.

**Comment by TheAntVenom** [comment]
I'm having an issue launching the Windows release version on Windows 11 24H2. v1.1.1 launches just fine. I've tried launching this on 3 separate machines. Two of which have NVIDIA based GPU's (one desktop, one mobile), and one of which has AMD Ryzen onboard graphics.

When I check Event Viewer, it shows that the application crashed, with the following error:
> Faulting application name: Zelda64Recompiled.exe, version: 0.0.0.0, time stamp: 0x668c4ec4
Faulting module name: MSVCP140.dll, version: 14.32.31326.0, time stamp: 0x7255e0ca
Exception code: 0xc0000005
Fault offset: 0x0000000000013278
Faulting process id: 0x831C
Faulting application start time: 0x1DADE39465D1393
Faulting application path: D:\Users\Tesseract\Desktop\Zelda64Recompiled-Windows-Release (2)\Zelda64Recompiled.exe
Faulting module path: C:\WINDOWS\SYSTEM32\MSVCP140.dll
Report Id: 5554ac97-fec9-4343-b084-7f65345e0fd9
Faulting package full name: 
Faulting package-relative application ID: 

I've tried re-installing the Visual Studio redistributable, to no avail.

**Comment by Mr-Wiseguy** [comment]
@TheAntVenom Could you try the latest CI build for this branch as well as the latest from the dev branch ([from here](https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9846543478))? If both fail to launch then the issue must be unrelated to HD textures and we'll need to investigate when it stopped launching for you, but if only this branch fails to launch then that narrows it down a lot.

**Comment by TheAntVenom** [comment]
> @TheAntVenom Could you try the latest CI build for this branch as well as the latest from the dev branch ([from here](https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9846543478))? If both fail to launch then the issue must be unrelated to HD textures and we'll need to investigate when it stopped launching for you, but if only this branch fails to launch then that narrows it down a lot.

Tried them both, and neither worked.

**Comment by Mr-Wiseguy** [comment]
What about the CI for [this build](https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9341013844)? This is the commit that 1.1.1 was made from, so it should work as a good sanity check.

**Comment by TheAntVenom** [comment]
> What about the CI for [this build](https://github.com/Zelda64Recomp/Zelda64Recomp/actions/runs/9341013844)? This is the commit that 1.1.1 was made from, so it should work as a good sanity check.

This one works.

**Comment by Mr-Wiseguy** [comment]
Okay, that confirms that it's unrelated to this branch or the CI at least. Since it's not related to the HD textures changes, can you open a new issue for this so we can discuss more there?

**Comment by Mr-Wiseguy** [comment]
For those watching this PR, the part that's been merged is just the underlying framework for HD textures. The actual menu for selecting texture packs will come later as part of the menu for loading mods in general.

**Comment by georgestylesidox** [comment]
> For those watching this PR, the part that's been merged is just the underlying framework for HD textures. The actual menu for selecting texture packs will come later as part of the menu for loading mods in general.

Awesome - we are getting closer :) will the dev branch still include the debug menu method of turning it on and selecting folder pls?

**Comment by Mr-Wiseguy** [comment]
Yeah, the F1 menu will remain intact since that's part of RT64's debugger.

**Pull request merged**
